#
#
#
#

myecho: myecho.c
	cc -o myecho myecho.c

mycat: mycat.c
	cc -o mycat mycat.c

mycp: mycp.c
	cc -o mycp mycp.c

mysys: mysys.c
	cc -o mysys mysys.c

sh1: sh1.c
	cc -o sh1 sh1.c

#addpath:
#	export PATH="$$PATH:/home/hadoop/test-system/job3"

clean: 
	rm -f *.o
